### ISSUE TITLE
Move request start/accept to DuplexConnection?

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveSocket/reactivesocket-java#13]
Today the interaction with the library in a client/server is as follows:

```java
DuplexConnection c = createConnection(); // Create from some factory
ReactiveSocketClientProtocol p = ReactiveSocketClientProtocol.create(c);
p.requestResponse("Hello).subscribe();
```

I see two issues with this approach:

- (Just a matter of taste) It looks to me that the request initiation belongs to the connection and the protocol abstraction seems unnecessary. So, it would look something like:

```java
DuplexConnection c = createConnection(); // Create from some factory
c.requestResponse("Hello).subscribe();
```

- The current model does not handle broken connections and re-connect. The reason being that the protocol class does not have the knowledge to re-create a connection. So, in order to solve this issue, we have to go either the way of providing the protocol class with a `Single<DuplexConnection>` or if we move these methods to the connection itself, we just `flatmap` the `Single` and do our stuff. The re-connect would just be a retry in either cases.

I have recently added a construct in RxNetty to cache a connection till it closes, which would be useful in this case as we would have multiple subscriptions to the `Single<DuplexConnection>` which would need to get the same `DuplexConnection` till it is valid. The relevant class is [here](https://github.com/ReactiveX/RxNetty/blob/0.5.x/rxnetty/src/main/java/io/reactivex/netty/protocol/http/ws/client/OperatorCacheSingleWebsocketConnection.java).

**Comment by tmontgomery** [comment]
Couple things.

1. Do we want to continue previous state when re-connecting. This is a fairly big decision because it means Stream IDs can persist across connections. It also means continuations of streams, etc.

1. We could use the spec naming of `Connection` that has `Requester` and `Responder` for each side of the connection. Requester and Responder would replace Client and Server. However, this is all internal. The exposed API should probably only be `Connection` or similar.

I think it would make sense to hide the protocol processing inside the Connection.

```java
ReactiveSocket.Connection c = createConnection(); // create from some factory
c.requestResponse("some endpoint").subscribe();
```

**Comment by benjchristensen** [comment]
> Do we want to continue previous state when re-connecting. 

We have decided no.

**Comment by benjchristensen** [comment]
We have changed the design quite a bit since this question. Closing out. Open a new one if current design has issues.
