### ISSUE TITLE
DuplexConnection.getInput() should return Publisher<Frame>?

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveSocket/reactivesocket-java#131]
#### Problem

This is the signature of `DuplexConnection.getInput()`

``` java
Observable<Frame> getInput();
```

where `Observable` is defined locally within `ReactiveSocket`. This seems unnecessary as it introduces one more abstraction where `Publisher` can be used. 
#### Proposal

Make the method return `Publisher<Frame>`
#### Result

Consistency of API and also reduced number of contracts we have to maintain.

**Comment by benjchristensen** [comment]
Well ... the reason for that is that `DuplexConnection` `getInput` doesn't support backpressure. It was consciously moved from `Publisher` to something that doesn't use `request(n)` because it was confusing for this to return `Publisher`, as all we can do is `request(Long.MAX_VALUE)`. You can't tell the incoming network to stop sending you data here.

**Comment by NiteshKant** [comment]
Yeah I guessed the reason!

So, do you think it is worth keeping that interface now? 
I think it is an implementation detail (from `ReactiveSocket`) to send `Long.MAX_VALUE` or determine a strategy to request some buffer size, so it doesn't really give much benefits introducing another concept out of reactive streams specs. WDYT?

**Comment by benjchristensen** [comment]
I prefer not using `Publisher` since that needs to be implemented by external developers and is harder to do, and I want the contract easier for them. But I can be swayed on this. I'd appreciate others weighing in. 

In more detail, I originally chose to make the change to using `Observable` instead of `Publisher` as I didn't want a `DuplexConnection` having to implement a `Publisher` and consider the `request(n)` semantics, as it makes is FAR harder to implement. And a `Publisher` can't be returned that just assumes `Long.MAX_VALUE` as then it breaks the `Publisher` contract in the event something else uses it expecting the correct contract. 

I would also very much like to see the `io.reactivesocket.rx` package go away. It's ugly to have, but can't go away unless we accept the complexity of using `Publisher`, or RxJava v2 is released and we accept it as a dependency for the public API. 

For me the strongest reason to not return `Publisher` is the complexity of implementation `request(n)` semantics correctly within the `Publisher`, which we then dutifully defeat by always calling `request(Long.MAX_VALUE)`.

**Comment by NiteshKant** [comment]
Personally I would like to keep away from pulling in RxJava or any other function composition library into any other modules apart from transport implementations. 
Currently I am trying to see if we use anything significant apart from `error()`, `just()`, `empty()` kind of simple functions. I haven't found anything worth pulling in a library for but I may be wrong.

IMHO transport implementations would not be huge in number and even if they are we _may_ want to encourage backpressure support as someday we may be smarter than sending `Long.MAX_VALUE` (eg: sum of all `requestN`s on the channel). So, I would prefer internal code maintainability (via lesser code in this case) over making transport implementations easier by ignoring backpressure. 

Those were my proverbial `$0.02` but yeah would like to hear what others have to say.

**Comment by benjchristensen** [comment]
> Personally I would like to keep away from pulling in RxJava or any other function composition library

Agreed. Which is why we didn't use them from the start.

> transport implementations would not be huge in number

That to me is not a good enough reason for using a type in a confusing way. The point is that we are either (1) requiring the transport implementations to take backpressure into account (which they can't really do anything about if it happens), or (2) breaking the contract of using `Publisher` if the implementations assume they will only ever receive `Long.MAX_VALUE`. For that reason I prefer the type being honest to the contract. We shouldn't abuse one type just to avoid having another when the other is more correct. 

> someday we may be smarter than sending Long.MAX_VALUE

Help me understand what you envision here. The way I see it is that bytes coming off the wire can't be flow controlled with 'request(n)`. They are pure push at that point. The opportunity for `request(n)` is at the application layer, which ReactiveSocket streams offers. But at the transport level we must handle it, drop, buffer, or block. Dropping and buffering are not decisions we want the DuplexConnection implementations doing. I doubt we want to block – particularly since we're trying to do flow control via 3 different mechanisms already: request(n), byte stream credits, and request leases. 

Thus I don't see a circumstance where we would use something other than `Long.MAX_VALUE` for the transport layer, since it really is a push data source where we just have to react.

What exactly is the problem being solved here? Why is having the extra `Observable` type an issue? Perhaps just renaming `Observable` to something more generic like `Stream` or `ByteStream`?

**Comment by NiteshKant** [comment]
Looks like the basic point of contention here is that you believe that `getInput()` can never be flow controlled on the network and I believe the other way round. So, let me explain my thinking on it.

__Inability to _accurately_ control the data(bytes) read does not mean that there are unbounded buffers on the network (i.e. `Long.MAX_VALUE`).__

FWIW, if we are talking about `request(n)` == `n Frames` then we already know the maximum data that can arrive for `n Frames`, since the maximum size of a frame is fixed. So, why not make the network aware about this?

Now, let us assume that `ReactiveSocket` is used for a single subscription that sends 1 item every minute. So, why in this case would we not tell the network that we are expecting only 1 `Frame`? This will help the network stop listening to read events unless more is requested.
Wouldn't we be able to protect against abusive/buggy servers (endpoints) which sends more data than requested and do so over slow congested networks?

**Comment by benjchristensen** [comment]
> does not mean that there are unbounded buffers on the network

I'm not saying they are unbounded. I'm saying that DuplexConnection.getInput() is not where we can provide flow control of the buffers.

> This will help the network stop listening to read events unless more is requested.

That's not really how I understand networks (or at least the code reading bytes off the network) behave, particularly on a bi-directional protocol where the other side can send something whenever it wants. And has leasing and keep alives that will always be sent, and we must receive, even if applying flow control to certain streams. 

We can't stop listening to the bytes via DuplexConnection, as high priority bytes need to come through for some parts of the protocol, while others may be limited by request(n), leasing, or byte windows.

> Wouldn't we be able to protect against abusive/buggy servers (endpoints) which sends more data than requested and do so over slow congested networks?

How does telling DuplexConnection a "request(n)" value enable this? We already have 3 mechanisms in place that are useful as part of the protocol:

a) request(n) for the application layer
b) leasing to prevent new requests
c) (soon to be added) byte credits (similar to HTTP/2 WINDOW_UPDATE) to control bytes per stream

Considering those three, what is DuplexConnection going to do more? And even if it could stop the bytes without causing them to buffer in the network layer, how does that not break the protocol behavior as discussed above with leasing, keep alives, etc that need to flow even if we're stopping the flow of some streams?

> So, why not make the network aware about this?

I don't know what this means. I don't see how we "make the network aware". Our options as I see them are:

a) use the three flow control mechanisms of ReactiveSocket, which is at the protocol layer above DuplexConnection, so that DuplexConnection is only receiving Frames/bytes that are permitted, expected, and capable of being handled.
b) buffer inside DuplexConnection (we are trying to avoid doing this)
c) drop/fail inside DuplexConnection (not really an option)
d) block the IO so that we apply backpressure on the underlying TCP by filling the network buffers (we are trying to avoid doing this)

**Comment by robertroeser** [comment]
I see no problem with supporting back-pressure in the duplex connection. The implementations I wrote would have been easier - esp. Aeron.  I could use back-pressure to choose when to spin and look for items  vs now where  I just spin.  There are utilities to deal with back pressure that DuplexConnection implementor could use. Using something else beside Publisher causes you have to write everything on your own. If you use Publisher you can delegate to a library that interacts with Publisher to deal with it. There isn't any documentation on Observable/Observer/Completable etc. vs Publisher.
