### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by rodneyparnell** [ReactiveSocket/reactivesocket-java#174]
I just found this project and it looks fantastic. What is the status? Is it ready for production use? Particularly aeron and tcp.
Thanks

**Comment by stevegury** [comment]
We're starting to use it internally at Netflix in some production system.
Expect lots of bug fixes and small improvements in the following weeks/months.

**Comment by rodneyparnell** [comment]
Great! How does it tie in with or contrast to your vision for Hystrix-Ribbon or Hystrix-gRPC? 
Will it get integrated with the Hystrix-style stack or is it a separate beast altogether?

**Comment by stevegury** [comment]
Hystrix won't be integrated inside reactivesocket, but could be integrated on top of it. Also, some features are already provided, c.f. [filters](https://github.com/ReactiveSocket/reactivesocket-java/tree/master/reactivesocket-client/src/main/java/io/reactivesocket/client/filter).
The design is different from Ribbon as it embraces non-blocking architecture but similar to gRPC.

**Comment by rodneyparnell** [comment]
Thanks for the info. 

A higher level question - are there different use cases for ReactiveSocket vs the existing Hystrix-gRPC direction? What drives adoption choices in Netflix for ReactiveSocket over the incumbent approach that has worked so well? (It seems to me that a major advantage of ReactiveSocket  might be the ability for continue a seamless reactive model through server tiers over TCP or Aeron all the way through to presentation tiers via websocket to RxJS-bases front-end).

**Comment by ktoso** [comment]
Project status is somewhat explained in: https://github.com/ReactiveSocket/reactivesocket-java/issues/175

Proposing to close this ticket here.

**Comment by NiteshKant** [comment]
@ktoso I agree, closing this issue.

@rodneyparnell 

My current belief is that we do not need Hystrix with `ReactiveSocket`, primarily because the features in hystrix are either built into `ReactiveSocket` or they are not useful with `ReactiveSocket`. Few of the examples are:

- Circuit Breaker: Almost equivalent to the features that `ReactiveSocket` load balancer provides.
- Thread isolation: Not required as `ReactiveSocket` uses non blocking I/O.
- Semaphore isolation: Not required as `ReactiveSocket` has request leasing which limits concurrency to a server.
- Request Collapsing: Not required as we have multiplexed requests on a single connection.
- Fallbacks: Client side fallbacks leads to leaking of business logic on the client and hence fat clients. Although, if required, can be easily implemented using RxJava.

But YMMV and there may be reasons why one would like to use Hystrix, for which as @stevegury  suggested, can be layered on top of `ReactiveSocket`
